service: js-api

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  hello_detail:
    handler: handler_detail.hello
    events:
      - http:
          path: hello/{id}
          method: get
        request:
          parameters:
            paths:
              id: true
